
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Royal Blue Anarkali Kurta',
    category: 'Anarkali',
    price: 1899,
    originalPrice: 3499,
    rating: 4.8,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop',
    description: 'A stunning royal blue Anarkali featuring gold zari work. Perfect for weddings and festive occasions.',
    colors: ['Royal Blue', 'Deep Maroon'],
    sizes: ['S', 'M', 'L', 'XL'],
    isBestSeller: true
  },
  {
    id: '2',
    name: 'Mustard Yellow Straight Kurti',
    category: 'Straight',
    price: 899,
    originalPrice: 1599,
    rating: 4.5,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop',
    description: 'Elegant straight-cut kurti in breathable cotton. Ideal for office wear and casual outings.',
    colors: ['Mustard', 'White'],
    sizes: ['XS', 'S', 'M', 'L'],
    isNew: true
  },
  {
    id: '3',
    name: 'Emerald Green A-Line Set',
    category: 'Ethnic Set',
    price: 2499,
    originalPrice: 4299,
    rating: 4.9,
    reviews: 56,
    image: 'https://images.unsplash.com/photo-1617175548916-1a20158390e5?q=80&w=800&auto=format&fit=crop',
    description: 'Complete ethnic set with printed dupatta and matching trousers. Crafted from premium rayon.',
    colors: ['Emerald Green', 'Peach'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    isBestSeller: true
  },
  {
    id: '4',
    name: 'Floral Print Short Kurti',
    category: 'Short',
    price: 649,
    originalPrice: 999,
    rating: 4.3,
    reviews: 210,
    image: 'https://images.unsplash.com/photo-1595991834974-958807204431?q=80&w=800&auto=format&fit=crop',
    description: 'Trendy short kurti with delicate floral prints. Pairs perfectly with denim for a fusion look.',
    colors: ['Sky Blue', 'Pink'],
    sizes: ['S', 'M', 'L'],
    isNew: true
  },
  {
    id: '5',
    name: 'Pastel Pink Embroidered Kurta',
    category: 'A-Line',
    price: 1299,
    originalPrice: 2199,
    rating: 4.7,
    reviews: 45,
    image: 'https://images.unsplash.com/photo-1627484350333-b295c960256e?q=80&w=800&auto=format&fit=crop',
    description: 'Chic A-line kurta with hand embroidery on the neckline. Versatile for both day and night.',
    colors: ['Pastel Pink', 'Mint'],
    sizes: ['S', 'M', 'L', 'XL'],
    isBestSeller: false
  },
  {
    id: '6',
    name: 'Classic White Chikankari',
    category: 'Straight',
    price: 1599,
    originalPrice: 2599,
    rating: 5.0,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1627484351109-433390c58a69?q=80&w=800&auto=format&fit=crop',
    description: 'Hand-crafted Lucknowi Chikankari work on pure georgette. A timeless masterpiece.',
    colors: ['White'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isBestSeller: true
  },
  {
    id: '7',
    name: 'Indigo Blue Handblock Print',
    category: 'Straight',
    price: 1199,
    originalPrice: 1999,
    rating: 4.6,
    reviews: 78,
    image: 'https://images.unsplash.com/photo-1621335322347-3ce413cad9d4?q=80&w=800&auto=format&fit=crop',
    description: 'Beautiful indigo blue handblock printed straight kurti. 100% natural dyes.',
    colors: ['Indigo'],
    sizes: ['S', 'M', 'L'],
    isNew: true
  },
  {
    id: '8',
    name: 'Maroon Festive Velvet Set',
    category: 'Ethnic Set',
    price: 3899,
    originalPrice: 5999,
    rating: 4.9,
    reviews: 32,
    image: 'https://images.unsplash.com/photo-1610030469668-935100028e0c?q=80&w=800&auto=format&fit=crop',
    description: 'Luxurious maroon velvet set with intricate zari work. Perfect for winter weddings.',
    colors: ['Maroon'],
    sizes: ['M', 'L', 'XL'],
    isBestSeller: true
  },
  {
    id: '9',
    name: 'Lavender Tiered Anarkali',
    category: 'Anarkali',
    price: 2199,
    originalPrice: 3899,
    rating: 4.8,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1595991834129-c0fe1608b842?q=80&w=800&auto=format&fit=crop',
    description: 'Breezy lavender tiered Anarkali with silver foil prints. High-fashion ethnic look.',
    colors: ['Lavender'],
    sizes: ['S', 'M', 'L'],
    isNew: true
  },
  {
    id: '10',
    name: 'Mirror Work Party Kurti',
    category: 'Short',
    price: 799,
    originalPrice: 1499,
    rating: 4.4,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1617175548270-349f2b844b20?q=80&w=800&auto=format&fit=crop',
    description: 'Vibrant yellow short kurti with heavy mirror work on the yoke. Boho-ethnic vibes.',
    colors: ['Yellow', 'Orange'],
    sizes: ['XS', 'S', 'M'],
    isBestSeller: false
  },
  {
    id: '11',
    name: 'Peach Cotton A-Line',
    category: 'A-Line',
    price: 999,
    originalPrice: 1799,
    rating: 4.5,
    reviews: 64,
    image: 'https://images.unsplash.com/photo-1583391733975-968600173395?q=80&w=800&auto=format&fit=crop',
    description: 'Simple and elegant peach cotton A-line kurta for daily comfort. Breathable fabric.',
    colors: ['Peach', 'Mint'],
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: false
  },
  {
    id: '12',
    name: 'Black Silk Embroidered',
    category: 'Straight',
    price: 2899,
    originalPrice: 4499,
    rating: 5.0,
    reviews: 21,
    image: 'https://images.unsplash.com/photo-1595991834381-81d06352996d?q=80&w=800&auto=format&fit=crop',
    description: 'Classic black chanderi silk kurti with sophisticated hand embroidery. Formal elegance.',
    colors: ['Black'],
    sizes: ['M', 'L', 'XL'],
    isBestSeller: true
  }
];

export const CATEGORIES = ['All', 'Anarkali', 'Straight', 'Short', 'A-Line', 'Ethnic Set'];
